version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    restart: always
    volumes:
      - ./backend/src:/src
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - checkbox


  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./var/postgres:/var/lib/postgresql/data/
    networks:
      - checkbox

networks:
  checkbox: